import ReduxProvider from '@src/redux/provider';
import './globals.scss';
import type { Metadata } from 'next';
import { Fira_Sans } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

const firaSans = Fira_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`sm:invisible lg:visible ${firaSans.className}`}>
        <ReduxProvider>
          <NextTopLoader showSpinner={false} easing="ease" />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
