import './index.scss';
import type { Metadata } from 'next';
import { Fira_Sans } from 'next/font/google';

import BuilderHeader from '@src/components/Layouts/Header/BuilderHeader';
import BuilderSidebar from '@src/components/Layouts/Sidebar/BuilderSidebar';

const firaSans = Fira_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Builder',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <BuilderHeader />
      <BuilderSidebar />
      <main className={`${firaSans.className} pt-[56px] pl-[52px] h-full`}>
        {children}
      </main>
    </>
  );
}
